//*******************************************************************
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject
// to the following conditions:
// 
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// 
// Description: scatti - pure C99 jerk-limited real-time trajectory
//              generation. Port of Ruckig with embed-friendly
//              memory and math hooks.
// Author:      杨阳 (Yang Yang) <mika-net@outlook.com>
// Origin:      Based on Ruckig Community Edition by Lars Berscheid
//              (https://github.com/pantor/ruckig)
// License:     MIT (SPDX-License-Identifier: MIT)
// Copyright (c) 2026 杨阳 (Yang Yang)
// *******************************************************************

//! Safe Rust bindings for **scatti** — jerk-limited real-time trajectory
//! generation.
//!
//! # Example
//! ```no_run
//! use scatti::{Ruckig, InputParameter, OutputParameter, Result};
//!
//! let mut ruckig = Ruckig::new(3, 0.01);
//! let mut input = InputParameter::new(3);
//! let mut output = OutputParameter::new(3);
//!
//! input.current_position_mut().copy_from_slice(&[0.0, 0.0, 0.5]);
//! input.target_position_mut().copy_from_slice(&[5.0, -2.0, -3.5]);
//! input.max_velocity_mut().copy_from_slice(&[3.0, 1.0, 3.0]);
//! input.max_acceleration_mut().copy_from_slice(&[3.0, 2.0, 1.0]);
//! input.max_jerk_mut().copy_from_slice(&[4.0, 3.0, 2.0]);
//!
//! loop {
//!     let res = ruckig.update(&input, &mut output);
//!     println!("t={:.3} pos={:?}", output.time(), output.new_position());
//!     output.pass_to_input(&mut input);
//!     match res {
//!         Result::Finished => break,
//!         Result::Working => {}
//!         _ => panic!("error"),
//!     }
//! }
//! ```

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

/// Raw FFI bindings generated by bindgen.
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::ptr;

// ---------------------------------------------------------------------------
// Result
// ---------------------------------------------------------------------------

/// Trajectory computation result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum Result {
    Working = 0,
    Finished = 1,
    Error = -1,
    ErrorInvalidInput = -100,
    ErrorTrajectoryDuration = -101,
    ErrorPositionalLimits = -102,
    ErrorZeroLimits = -104,
    ErrorExecutionTimeCalculation = -110,
    ErrorSynchronizationCalculation = -111,
}

impl From<ffi::SCattiResult> for Result {
    fn from(v: ffi::SCattiResult) -> Self {
        match v {
            0 => Result::Working,
            1 => Result::Finished,
            -100 => Result::ErrorInvalidInput,
            -101 => Result::ErrorTrajectoryDuration,
            -102 => Result::ErrorPositionalLimits,
            -104 => Result::ErrorZeroLimits,
            -110 => Result::ErrorExecutionTimeCalculation,
            -111 => Result::ErrorSynchronizationCalculation,
            _ => Result::Error,
        }
    }
}

// ---------------------------------------------------------------------------
// ControlInterface / Synchronization / DurationDiscretization
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ControlInterface {
    Position = 0,
    Velocity = 1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum Synchronization {
    Time = 0,
    TimeIfNecessary = 1,
    Phase = 2,
    No = 3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum DurationDiscretization {
    Continuous = 0,
    Discrete = 1,
}

// ---------------------------------------------------------------------------
// InputParameter
// ---------------------------------------------------------------------------

/// Motion input parameters (current/target state & limits).
pub struct InputParameter {
    ptr: *mut ffi::SCattiInputParameter,
    dofs: usize,
}

macro_rules! input_array_accessors {
    ($getter:ident, $getter_mut:ident, $field:ident) => {
        pub fn $getter(&self) -> &[f64] {
            unsafe { std::slice::from_raw_parts((*self.ptr).$field, self.dofs) }
        }
        pub fn $getter_mut(&mut self) -> &mut [f64] {
            unsafe { std::slice::from_raw_parts_mut((*self.ptr).$field, self.dofs) }
        }
    };
}

impl InputParameter {
    pub fn new(dofs: usize) -> Self {
        let ptr = unsafe { ffi::scatti_input_create(dofs) };
        assert!(!ptr.is_null(), "scatti_input_create returned NULL");
        Self { ptr, dofs }
    }

    pub fn degrees_of_freedom(&self) -> usize {
        self.dofs
    }

    input_array_accessors!(current_position, current_position_mut, current_position);
    input_array_accessors!(current_velocity, current_velocity_mut, current_velocity);
    input_array_accessors!(current_acceleration, current_acceleration_mut, current_acceleration);
    input_array_accessors!(target_position, target_position_mut, target_position);
    input_array_accessors!(target_velocity, target_velocity_mut, target_velocity);
    input_array_accessors!(target_acceleration, target_acceleration_mut, target_acceleration);
    input_array_accessors!(max_velocity, max_velocity_mut, max_velocity);
    input_array_accessors!(max_acceleration, max_acceleration_mut, max_acceleration);
    input_array_accessors!(max_jerk, max_jerk_mut, max_jerk);

    // --- optional arrays ---
    pub fn set_min_velocity(&mut self, values: &[f64]) {
        assert_eq!(values.len(), self.dofs);
        unsafe {
            if (*self.ptr).min_velocity.is_null() {
                (*self.ptr).min_velocity = libc_calloc_f64(self.dofs);
            }
            ptr::copy_nonoverlapping(values.as_ptr(), (*self.ptr).min_velocity, self.dofs);
        }
    }

    pub fn set_min_acceleration(&mut self, values: &[f64]) {
        assert_eq!(values.len(), self.dofs);
        unsafe {
            if (*self.ptr).min_acceleration.is_null() {
                (*self.ptr).min_acceleration = libc_calloc_f64(self.dofs);
            }
            ptr::copy_nonoverlapping(values.as_ptr(), (*self.ptr).min_acceleration, self.dofs);
        }
    }

    pub fn set_enabled(&mut self, values: &[bool]) {
        assert_eq!(values.len(), self.dofs);
        unsafe {
            if (*self.ptr).enabled.is_null() {
                (*self.ptr).enabled = libc::calloc(self.dofs, std::mem::size_of::<bool>()) as *mut bool;
            }
            for i in 0..self.dofs {
                *(*self.ptr).enabled.add(i) = values[i];
            }
        }
    }

    // --- enum properties ---
    pub fn set_control_interface(&mut self, ci: ControlInterface) {
        unsafe { (*self.ptr).control_interface = ci as u32; }
    }

    pub fn set_synchronization(&mut self, sync: Synchronization) {
        unsafe { (*self.ptr).synchronization = sync as u32; }
    }

    pub fn set_duration_discretization(&mut self, dd: DurationDiscretization) {
        unsafe { (*self.ptr).duration_discretization = dd as u32; }
    }

    pub fn set_minimum_duration(&mut self, d: Option<f64>) {
        unsafe {
            match d {
                Some(v) => {
                    (*self.ptr).minimum_duration = v;
                    (*self.ptr).has_minimum_duration = true;
                }
                None => {
                    (*self.ptr).has_minimum_duration = false;
                }
            }
        }
    }

    // --- Pro features ---

    /// Set intermediate waypoints. Each inner slice must have `dofs` elements.
    pub fn set_intermediate_positions(&mut self, waypoints: &[&[f64]]) {
        if waypoints.is_empty() {
            unsafe { ffi::scatti_input_set_intermediate_positions(self.ptr, ptr::null(), 0); }
            return;
        }
        let n = waypoints.len();
        let mut flat = vec![0.0; n * self.dofs];
        for (i, wp) in waypoints.iter().enumerate() {
            assert_eq!(wp.len(), self.dofs, "waypoint {i} has wrong size");
            flat[i * self.dofs..(i + 1) * self.dofs].copy_from_slice(wp);
        }
        unsafe {
            ffi::scatti_input_set_intermediate_positions(self.ptr, flat.as_ptr(), n);
        }
    }

    pub fn set_max_position(&mut self, values: &[f64]) {
        assert_eq!(values.len(), self.dofs);
        unsafe {
            if (*self.ptr).max_position.is_null() {
                (*self.ptr).max_position = libc_calloc_f64(self.dofs);
            }
            ptr::copy_nonoverlapping(values.as_ptr(), (*self.ptr).max_position, self.dofs);
        }
    }

    pub fn set_min_position(&mut self, values: &[f64]) {
        assert_eq!(values.len(), self.dofs);
        unsafe {
            if (*self.ptr).min_position.is_null() {
                (*self.ptr).min_position = libc_calloc_f64(self.dofs);
            }
            ptr::copy_nonoverlapping(values.as_ptr(), (*self.ptr).min_position, self.dofs);
        }
    }

    pub fn set_interrupt_calculation_duration(&mut self, duration_us: f64) {
        unsafe { (*self.ptr).interrupt_calculation_duration = duration_us; }
    }

    pub fn validate(&self, check_current: bool, check_target: bool) -> bool {
        unsafe { ffi::scatti_input_validate(self.ptr, check_current, check_target) }
    }

    pub(crate) fn as_ptr(&self) -> *mut ffi::SCattiInputParameter {
        self.ptr
    }
}

impl Drop for InputParameter {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { ffi::scatti_input_destroy(self.ptr); }
            self.ptr = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// OutputParameter
// ---------------------------------------------------------------------------

/// Motion output (new state after one control cycle).
pub struct OutputParameter {
    ptr: *mut ffi::SCattiOutputParameter,
    dofs: usize,
}

impl OutputParameter {
    pub fn new(dofs: usize) -> Self {
        let ptr = unsafe { ffi::scatti_output_create(dofs) };
        assert!(!ptr.is_null(), "scatti_output_create returned NULL");
        Self { ptr, dofs }
    }

    pub fn degrees_of_freedom(&self) -> usize {
        self.dofs
    }

    pub fn new_position(&self) -> &[f64] {
        unsafe { std::slice::from_raw_parts((*self.ptr).new_position, self.dofs) }
    }

    pub fn new_velocity(&self) -> &[f64] {
        unsafe { std::slice::from_raw_parts((*self.ptr).new_velocity, self.dofs) }
    }

    pub fn new_acceleration(&self) -> &[f64] {
        unsafe { std::slice::from_raw_parts((*self.ptr).new_acceleration, self.dofs) }
    }

    pub fn new_jerk(&self) -> &[f64] {
        unsafe { std::slice::from_raw_parts((*self.ptr).new_jerk, self.dofs) }
    }

    pub fn time(&self) -> f64 {
        unsafe { (*self.ptr).time }
    }

    pub fn new_section(&self) -> usize {
        unsafe { (*self.ptr).new_section }
    }

    pub fn did_section_change(&self) -> bool {
        unsafe { (*self.ptr).did_section_change }
    }

    pub fn new_calculation(&self) -> bool {
        unsafe { (*self.ptr).new_calculation }
    }

    pub fn was_calculation_interrupted(&self) -> bool {
        unsafe { (*self.ptr).was_calculation_interrupted }
    }

    pub fn calculation_duration(&self) -> f64 {
        unsafe { (*self.ptr).calculation_duration }
    }

    /// Access the computed trajectory.
    pub fn trajectory(&self) -> Trajectory<'_> {
        Trajectory {
            ptr: unsafe { (*self.ptr).trajectory },
            dofs: self.dofs,
            _marker: std::marker::PhantomData,
        }
    }

    /// Copy output state back into input for the next control cycle.
    pub fn pass_to_input(&self, inp: &mut InputParameter) {
        unsafe { ffi::scatti_output_pass_to_input(self.ptr, inp.as_ptr()); }
    }

    pub(crate) fn as_ptr(&mut self) -> *mut ffi::SCattiOutputParameter {
        self.ptr
    }
}

impl Drop for OutputParameter {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { ffi::scatti_output_destroy(self.ptr); }
            self.ptr = ptr::null_mut();
        }
    }
}

// ---------------------------------------------------------------------------
// Trajectory (borrowed view)
// ---------------------------------------------------------------------------

/// Read-only view into a computed trajectory.
pub struct Trajectory<'a> {
    ptr: *mut ffi::SCattiTrajectory,
    dofs: usize,
    _marker: std::marker::PhantomData<&'a ()>,
}

impl Trajectory<'_> {
    pub fn duration(&self) -> f64 {
        unsafe { ffi::scatti_trajectory_get_duration(self.ptr) }
    }

    /// Sample the trajectory at a given time.
    pub fn at_time(&self, time: f64) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
        let mut pos = vec![0.0; self.dofs];
        let mut vel = vec![0.0; self.dofs];
        let mut acc = vec![0.0; self.dofs];
        let mut jrk = vec![0.0; self.dofs];
        let mut sec: usize = 0;
        unsafe {
            ffi::scatti_trajectory_at_time(
                self.ptr,
                time,
                pos.as_mut_ptr(),
                vel.as_mut_ptr(),
                acc.as_mut_ptr(),
                jrk.as_mut_ptr(),
                &mut sec,
            );
        }
        (pos, vel, acc, jrk)
    }

    pub fn get_independent_min_durations(&self) -> Vec<f64> {
        let mut out = vec![0.0; self.dofs];
        unsafe {
            ffi::scatti_trajectory_get_independent_min_durations(self.ptr, out.as_mut_ptr());
        }
        out
    }

    pub fn get_first_time_at_position(&self, dof: usize, position: f64, time_after: f64) -> Option<f64> {
        let mut t: f64 = 0.0;
        let found = unsafe {
            ffi::scatti_trajectory_get_first_time_at_position(
                self.ptr, dof, position, &mut t, time_after,
            )
        };
        if found { Some(t) } else { None }
    }
}

// ---------------------------------------------------------------------------
// Ruckig
// ---------------------------------------------------------------------------

/// Main trajectory generator.
pub struct Ruckig {
    ptr: *mut ffi::SCatti,
    dofs: usize,
}

impl Ruckig {
    /// Create a new trajectory generator for `dofs` degrees of freedom
    /// with the given control cycle `delta_time` (seconds).
    pub fn new(dofs: usize, delta_time: f64) -> Self {
        let ptr = unsafe { ffi::scatti_create(dofs, delta_time) };
        assert!(!ptr.is_null(), "scatti_create returned NULL");
        Self { ptr, dofs }
    }

    /// Create with waypoint support.
    pub fn new_with_waypoints(dofs: usize, delta_time: f64, max_waypoints: usize) -> Self {
        let ptr = unsafe { ffi::scatti_create_waypoints(dofs, delta_time, max_waypoints) };
        assert!(!ptr.is_null(), "scatti_create_waypoints returned NULL");
        Self { ptr, dofs }
    }

    pub fn degrees_of_freedom(&self) -> usize {
        self.dofs
    }

    pub fn reset(&mut self) {
        unsafe { ffi::scatti_reset(self.ptr); }
    }

    pub fn validate_input(&self, inp: &InputParameter, check_current: bool, check_target: bool) -> bool {
        unsafe { ffi::scatti_validate_input(self.ptr, inp.as_ptr(), check_current, check_target) }
    }

    /// Advance one control cycle.
    pub fn update(&mut self, inp: &InputParameter, out: &mut OutputParameter) -> Result {
        let rc = unsafe { ffi::scatti_update(self.ptr, inp.as_ptr(), out.as_ptr()) };
        Result::from(rc)
    }
}

impl Drop for Ruckig {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { ffi::scatti_destroy(self.ptr); }
            self.ptr = ptr::null_mut();
        }
    }
}

// Send + Sync are safe because the C library has no global mutable state.
unsafe impl Send for Ruckig {}
unsafe impl Send for InputParameter {}
unsafe impl Send for OutputParameter {}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn libc_calloc_f64(n: usize) -> *mut f64 {
    unsafe { libc::calloc(n, std::mem::size_of::<f64>()) as *mut f64 }
}

// Re-export libc for internal use
mod libc {
    extern "C" {
        pub fn calloc(nmemb: usize, size: usize) -> *mut std::ffi::c_void;
    }
}
